import { randomUUID } from 'node:crypto';
import type { Pool, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import type { RaisedTask, TaskReviewRepository } from './task-review';

interface TaskRow extends RowDataPacket { id:string; creator_employee_id:string; review_state:RaisedTask['reviewState']; version:number }
export class MysqlTaskReviewRepository implements TaskReviewRepository {
  constructor(private pool:Pool,private today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka'}).format(new Date())){}
  async employeeForUser(userId:string){const d=this.today();const[rows]=await this.pool.execute<(RowDataPacket&{id:string;lead_employee_id:string|null;division_id:string|null})[]>('SELECT e.id,a.lead_employee_id,a.division_id FROM employees e LEFT JOIN employee_division_assignments a ON a.employee_id=e.id AND a.is_active=TRUE AND a.effective_from<=? AND(a.effective_to IS NULL OR a.effective_to>=?) WHERE e.user_id=? AND e.status=\'active\'',[d,d,userId]);if(!rows[0])return null;return{id:rows[0].id,leadEmployeeId:rows.find(r=>r.lead_employee_id)?.lead_employee_id??null,divisionIds:[...new Set(rows.map(r=>r.division_id).filter((v):v is string=>v!==null))]}}
  async currentLeadForEmployee(id:string){const d=this.today();const[rows]=await this.pool.execute<(RowDataPacket&{lead_employee_id:string})[]>('SELECT lead_employee_id FROM employee_division_assignments WHERE employee_id=? AND is_active=TRUE AND is_primary=TRUE AND effective_from<=? AND(effective_to IS NULL OR effective_to>=?) LIMIT 1',[id,d,d]);return rows[0]?.lead_employee_id??null}
  async projectAvailable(id:string,employeeId:string,divisionIds:readonly string[]){if(!divisionIds.length)return false;const marks=divisionIds.map(()=>'?').join(',');const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT 1 FROM projects p WHERE p.id=? AND p.is_active=TRUE AND p.status='active' AND p.division_id IN(${marks}) AND EXISTS(SELECT 1 FROM employee_division_assignments a WHERE a.employee_id=? AND a.division_id=p.division_id AND a.is_active=TRUE AND a.effective_from<=? AND(a.effective_to IS NULL OR a.effective_to>=?))`,[id,...divisionIds,employeeId,this.today(),this.today()]);return Boolean(rows[0])}
  async insertRaised(i:Parameters<TaskReviewRepository['insertRaised']>[0]){const id=randomUUID();await this.pool.execute("INSERT INTO tasks(id,project_id,division_id,title,status,priority,assignee_employee_id,creator_employee_id,creator_role,estimated_minutes,due_date,description,review_state) SELECT ?,p.id,p.division_id,?,'pending',?,?,?,'employee',?,?,?,'pending_review' FROM projects p WHERE p.id=?",[id,i.title,i.priority,i.employeeId,i.employeeId,i.estimatedMinutes,i.dueDate,i.description,i.projectId]);return id}
  async find(id:string){const[rows]=await this.pool.execute<TaskRow[]>('SELECT id,creator_employee_id,review_state,version FROM tasks WHERE id=? LIMIT 1',[id]);const r=rows[0];return r?{id:r.id,creatorEmployeeId:r.creator_employee_id,reviewState:r.review_state,version:r.version}:null}
  async decideAtomic(i:Parameters<TaskReviewRepository['decideAtomic']>[0]){const c=await this.pool.getConnection();try{await c.beginTransaction();const[prior]=await c.execute<RowDataPacket[]>('SELECT id FROM task_review_decisions WHERE reviewer_employee_id=? AND idempotency_key=?',[i.reviewerEmployeeId,i.idempotencyKey]);if(prior[0]){await c.rollback();return'replayed' as const}const[result]=await c.execute<ResultSetHeader>("UPDATE tasks SET review_state=?,reviewer_employee_id=?,reviewed_at=UTC_TIMESTAMP(6),review_note=?,version=version+1 WHERE id=? AND version=? AND review_state='pending_review'",[i.outcome,i.reviewerEmployeeId,i.note,i.taskId,i.expectedVersion]);if(result.affectedRows!==1){await c.rollback();return'conflict' as const}await c.execute('INSERT INTO task_review_decisions(id,task_id,reviewer_employee_id,outcome,note,decided_at,idempotency_key,task_version)VALUES(?,?,?,?,?,UTC_TIMESTAMP(6),?,?)',[randomUUID(),i.taskId,i.reviewerEmployeeId,i.outcome,i.note,i.idempotencyKey,i.expectedVersion+1]);await c.commit();return'applied' as const}catch(e){await c.rollback();if((e as{code?:string}).code==='ER_DUP_ENTRY')return'conflict' as const;throw e}finally{c.release()}}
}
