import {taskAcceptsTime,type TaskReviewState} from '@/contracts/domain';
import type {ResultWarning,ValidationFailure} from '@/contracts/results';

const fieldError=(field:string,code:string,message:string,guidance:string):ValidationFailure=>({status:'validation_failure',code:'VALIDATION_FAILED',message:'Review the highlighted fields.',fieldErrors:[{field,code,message,guidance}],focusField:field});

export function validateAssignment(input:{startDate:string;endDate:string|null;isTemporary:boolean;allocationPercent:number}){
  if(input.isTemporary&&!input.endDate)return fieldError('endDate','TEMPORARY_END_REQUIRED','A temporary assignment needs an end date.','Choose the final date of the temporary assignment.');
  if(input.endDate&&input.endDate<input.startDate)return fieldError('endDate','INVALID_DATE_RANGE','The end date is before the start date.','Choose an end date on or after the start date.');
  if(!Number.isInteger(input.allocationPercent)||input.allocationPercent<0||input.allocationPercent>100)return fieldError('allocationPercent','INVALID_ALLOCATION','Allocation must be a whole percentage from 0 to 100.','Enter a whole number between 0 and 100.');
  return null;
}

export function allocationWarning(totalPercent:number):readonly ResultWarning[]{return totalPercent===100?[]:[{code:'ALLOCATION_NOT_100_PERCENT',field:'allocationPercent',message:`Concurrent planned allocation is ${totalPercent}%; review it against the expected 100%.`}]}
export function assignmentEffective(input:{startDate:string;endDate:string|null;isActive:boolean},date:string){return input.isActive&&input.startDate<=date&&(!input.endDate||input.endDate>=date);}
export function validateProject(input:{divisionId:string;managerDivisionIds:readonly string[];completionPercent:number;startDate:string|null;endDate:string|null}){if(!input.divisionId)return fieldError('divisionId','DIVISION_REQUIRED','A project belongs to exactly one division.','Choose one division.');if(!input.managerDivisionIds.includes(input.divisionId))return fieldError('managerEmployeeId','MANAGER_OUT_OF_SCOPE','The manager is not assigned to this division.','Choose a manager with an effective assignment in the project division.');if(!Number.isInteger(input.completionPercent)||input.completionPercent<0||input.completionPercent>100)return fieldError('completionPercent','INVALID_PERCENT','Completion must be from 0 to 100 percent.','Enter a whole percentage from 0 to 100.');if(input.startDate&&input.endDate&&input.endDate<input.startDate)return fieldError('endDate','INVALID_DATE_RANGE','The project end date is before its start date.','Choose an end date on or after the start date.');return null;}
export function validateTaskScope(input:{taskDivisionId:string;projectDivisionId:string;assigneeDivisionIds:readonly string[]}){if(input.taskDivisionId!==input.projectDivisionId)return fieldError('divisionId','TASK_PROJECT_DIVISION_MISMATCH','The task and project divisions do not match.','Use the project division.');if(!input.assigneeDivisionIds.includes(input.projectDivisionId))return fieldError('assigneeEmployeeId','ASSIGNEE_OUT_OF_SCOPE','The assignee is not assigned to the project division.','Choose an employee with an effective division assignment.');return null;}
export function taskDerivedFacts(entries:readonly {activeMinutes:number;isActive:boolean}[],status:'pending'|'in_progress'|'completed',dueDate:string|null,today:string){return{actualMinutes:entries.filter(e=>e.isActive).reduce((sum,e)=>sum+e.activeMinutes,0),isOverdue:status!=='completed'&&dueDate!==null&&dueDate<today};}
export function validateTaskForTime(input:{projectActive:boolean;projectAcceptsTime:boolean;authorized:boolean;reviewState:TaskReviewState}){if(!input.projectActive||!input.projectAcceptsTime)return fieldError('projectId','PROJECT_NOT_ACCEPTING_TIME','That project does not accept new time.','Choose an active project that accepts time.');if(!input.authorized)return fieldError('taskId','TASK_NOT_AUTHORIZED','That task is not available to you.','Choose an authorized task in the selected project.');if(!taskAcceptsTime(input.reviewState))return fieldError('taskId',input.reviewState==='rejected'?'TASK_REVIEW_REJECTED':'TASK_AWAITING_REVIEW','That task has not been approved for time.','Choose another task or wait for your Team Lead decision.');return null;}
