import 'server-only';
import { randomUUID } from 'node:crypto';
import type { Pool, RowDataPacket } from 'mysql2/promise';
import type { TaskReviewService, EmployeeTaskOptionsView, TaskReviewQueueView, TaskReviewStateView } from '@/contracts/task-review';
import type { Result } from '@/contracts/results';
import { success } from '@/contracts/results';
import { formatDate, formatTimestamp } from '@/lib/format';
import { toDurationView } from '@/lib/status';
import { AuditWriter, MysqlAuditSink } from '@/server/audit/writer';
import { MysqlTaskReviewEffects } from './mysql-task-review-effects';
import { MysqlTaskReviewRepository } from './mysql-task-review';
import { TaskReviewApplicationService } from './task-review';
import { AuthenticationService } from '@/server/authentication/service';
import { MysqlAuthenticationStore } from '@/server/authentication/mysql-store';

type Row=RowDataPacket&Record<string,unknown>;
const absent=():Result<never>=>({status:'not_found',code:'NOT_FOUND',message:'Task was not found.',resource:'task'});
const stateView=(row:{review_state:unknown;review_note?:unknown;reviewed_at?:unknown;reviewer_name?:unknown}):TaskReviewStateView=>{const state=String(row.review_state) as TaskReviewStateView['state'];return{state,label:{not_required:'Assigned',pending_review:'Awaiting review',approved:'Approved',rejected:'Not approved'}[state],detail:{not_required:'Assigned by a Team Lead; no review is required.',pending_review:'The Team Lead must review this task before it can receive work.',approved:'The Team Lead approved this task.',rejected:'The Team Lead did not approve this task.'}[state],blocksTimeEntry:state==='pending_review'||state==='rejected',reviewerName:row.reviewer_name?String(row.reviewer_name):null,reviewedAtLabel:row.reviewed_at?formatTimestamp(row.reviewed_at instanceof Date?row.reviewed_at.toISOString():String(row.reviewed_at)):null,note:row.review_note?String(row.review_note):null};};

export class BackendTaskReviewViews implements TaskReviewService {
  private readonly auth:AuthenticationService;private readonly repo:MysqlTaskReviewRepository;private readonly app:TaskReviewApplicationService;
  constructor(private readonly pool:Pool,private readonly sessionToken:string){this.auth=new AuthenticationService(new MysqlAuthenticationStore(pool));this.repo=new MysqlTaskReviewRepository(pool);this.app=new TaskReviewApplicationService(this.repo,new MysqlTaskReviewEffects(pool,new AuditWriter(new MysqlAuditSink(pool))));}
  private async identity(userId:string){const session=await this.auth.validateSession(this.sessionToken);return session.status==='success'&&session.data.userId===userId;}
  async options(userId:string):Promise<Result<EmployeeTaskOptionsView>>{if(!await this.identity(userId))return absent();const employee=await this.repo.employeeForUser(userId);if(!employee)return absent();const marks=employee.divisionIds.map(()=>'?').join(',')||"''";const [rows]=await this.pool.execute<Row[]>(`SELECT id,project_code,name,end_date FROM projects WHERE is_active=TRUE AND status='active' AND accepts_time_entries=TRUE AND division_id IN (${marks}) ORDER BY project_code`,employee.divisionIds);let reviewerName:string|null=null;if(!employee.isTeamLead&&employee.leadEmployeeId){const [lead]=await this.pool.execute<Row[]>('SELECT display_name FROM employees WHERE id=?',[employee.leadEmployeeId]);reviewerName=lead[0]?String(lead[0].display_name):null;}const requiresReview=!employee.isTeamLead;return success({projects:rows.map(row=>({value:String(row.id),label:`${String(row.project_code)} · ${String(row.name)}`})),canCreate:rows.length>0&&(!requiresReview||Boolean(employee.leadEmployeeId)),createBlockedReason:requiresReview&&!employee.leadEmployeeId?'You have no Team Lead assigned. Contact HR.':rows.length?null:'You are not assigned to a division with an active project.',requiresReview,reviewerName,maxDueDateHint:new Date().toISOString().slice(0,10)});}
  async create(userId:string,input:Parameters<TaskReviewService['create']>[1]){if(!await this.identity(userId))return absent();return this.app.raise(userId,input);}
  async queue(userId:string):Promise<Result<TaskReviewQueueView>>{if(!await this.identity(userId))return absent();const employee=await this.repo.employeeForUser(userId);if(!employee||!employee.isTeamLead)return success({rows:[],awaitingCount:0,href:'/tasks'});const [rows]=await this.pool.execute<Row[]>(`SELECT t.id,t.title,t.priority,t.due_date,t.estimated_minutes,t.description,t.created_at,p.project_code,p.name project_name,d.division_key,e.display_name creator_name FROM tasks t JOIN projects p ON p.id=t.project_id JOIN divisions d ON d.id=t.division_id JOIN employees e ON e.id=t.creator_employee_id JOIN employee_division_assignments a ON a.employee_id=t.creator_employee_id AND a.is_active=TRUE AND a.effective_from<=CURRENT_DATE AND (a.effective_to IS NULL OR a.effective_to>=CURRENT_DATE) LEFT JOIN departments dept ON dept.id=a.department_id AND dept.is_active=TRUE LEFT JOIN department_lead_assignments dla ON dla.department_id=dept.id AND dla.effective_from<=CURRENT_DATE AND (dla.effective_to IS NULL OR dla.effective_to>=CURRENT_DATE) WHERE t.review_state='pending_review' AND COALESCE(dla.lead_employee_id,a.lead_employee_id)=? GROUP BY t.id ORDER BY t.created_at`,[employee.id]);const result=rows.map(row=>({id:String(row.id),title:String(row.title),projectLabel:`${String(row.project_code)} · ${String(row.project_name)}`,divisionCode:String(row.division_key),requestedByName:String(row.creator_name),priority:String(row.priority??'medium') as TaskReviewQueueView['rows'][number]['priority'],dueDateLabel:row.due_date?formatDate(row.due_date instanceof Date?row.due_date.toISOString().slice(0,10):String(row.due_date)):null,estimated:toDurationView(Number(row.estimated_minutes??0)),description:row.description?String(row.description):null,requestedAtLabel:formatTimestamp(row.created_at instanceof Date?row.created_at.toISOString():String(row.created_at)),href:`/tasks/${String(row.id)}`}));return success({rows:result,awaitingCount:result.length,href:'/tasks'});}
  async decide(userId:string,taskId:string,input:Parameters<TaskReviewService['decide']>[2]){if(!await this.identity(userId))return absent();const result=await this.app.decide(userId,taskId,{...input,idempotencyKey:randomUUID()});if(result.status!=='success')return result;const [rows]=await this.pool.execute<Row[]>(`SELECT t.review_state,t.review_note,t.reviewed_at,e.display_name reviewer_name FROM tasks t LEFT JOIN employees e ON e.id=t.reviewer_employee_id WHERE t.id=?`,[taskId]);return rows[0]?success(stateView(rows[0] as Row&{review_state:unknown})):absent();}
}
