-- BE-0110..BE-0134: initial MySQL 8.4 schema foundation.
-- Recovery: before production traffic, restore the pre-migration backup or run
-- drizzle/recovery/0001_initial_foundation.sql only on a confirmed empty schema.

CREATE TABLE users (
  id CHAR(36) PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(254) NOT NULL,
  email_normalized VARCHAR(254) NOT NULL, employee_identifier VARCHAR(64), email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  image_url VARCHAR(1024), status ENUM('active','inactive','locked') NOT NULL DEFAULT 'active', two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  failed_login_count INT UNSIGNED NOT NULL DEFAULT 0, locked_until DATETIME(6), last_login_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_users_email (email_normalized), UNIQUE KEY uq_users_employee_identifier (employee_identifier)
) ENGINE=InnoDB;

CREATE TABLE auth_accounts (
  id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, provider_id VARCHAR(64) NOT NULL, account_id VARCHAR(191) NOT NULL,
  password_hash VARCHAR(255), access_token_encrypted TEXT, refresh_token_encrypted TEXT, token_expires_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_auth_account (provider_id, account_id), CONSTRAINT fk_auth_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
CREATE TABLE auth_sessions (
  id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, token_hash CHAR(64) NOT NULL, expires_at DATETIME(6) NOT NULL,
  revoked_at DATETIME(6), ip_address VARCHAR(45), user_agent VARCHAR(512), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE KEY uq_auth_sessions_token (token_hash),
  KEY ix_auth_sessions_user_expiry (user_id, expires_at), CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
CREATE TABLE auth_verifications (
  id CHAR(36) PRIMARY KEY, identifier_hash CHAR(64) NOT NULL, value_hash CHAR(64) NOT NULL, purpose VARCHAR(48) NOT NULL,
  expires_at DATETIME(6) NOT NULL, consumed_at DATETIME(6), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY ix_auth_verifications_lookup (identifier_hash, purpose, expires_at)
) ENGINE=InnoDB;
CREATE TABLE login_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id CHAR(36), identifier_hash CHAR(64) NOT NULL, outcome VARCHAR(32) NOT NULL,
  ip_address VARCHAR(45), user_agent VARCHAR(512), occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY ix_login_history_user_time (user_id, occurred_at), CONSTRAINT fk_login_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE roles (id CHAR(36) PRIMARY KEY, role_key VARCHAR(64) NOT NULL, name VARCHAR(100) NOT NULL, is_system BOOLEAN NOT NULL DEFAULT TRUE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_roles_key (role_key)) ENGINE=InnoDB;
CREATE TABLE permissions (id CHAR(36) PRIMARY KEY, permission_key VARCHAR(128) NOT NULL, name VARCHAR(160) NOT NULL, sensitivity ENUM('normal','protected','financial','government') NOT NULL DEFAULT 'normal', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_permissions_key (permission_key)) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id CHAR(36) NOT NULL, permission_id CHAR(36) NOT NULL, PRIMARY KEY(role_id, permission_id), CONSTRAINT fk_role_permissions_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE RESTRICT, CONSTRAINT fk_role_permissions_permission FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE user_roles (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, role_id CHAR(36) NOT NULL, effective_from DATE NOT NULL, effective_to DATE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_user_role_range(user_id, role_id, effective_from), CHECK(effective_to IS NULL OR effective_to >= effective_from), CONSTRAINT fk_user_roles_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_user_roles_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE divisions (id CHAR(36) PRIMARY KEY, division_key VARCHAR(64) NOT NULL, name VARCHAR(160) NOT NULL, is_government BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_divisions_key(division_key), UNIQUE KEY uq_divisions_name(name)) ENGINE=InnoDB;
CREATE TABLE employees (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, employee_code VARCHAR(64) NOT NULL, display_name VARCHAR(160) NOT NULL, job_title VARCHAR(160), hire_date DATE, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_employees_user(user_id), UNIQUE KEY uq_employees_code(employee_code), CONSTRAINT fk_employees_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE teams (id CHAR(36) PRIMARY KEY, division_id CHAR(36) NOT NULL, name VARCHAR(160) NOT NULL, lead_employee_id CHAR(36), effective_from DATE NOT NULL, effective_to DATE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_teams_division_name(division_id,name), CHECK(effective_to IS NULL OR effective_to >= effective_from), CONSTRAINT fk_teams_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_teams_lead FOREIGN KEY(lead_employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE employee_division_assignments (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, division_id CHAR(36) NOT NULL, team_id CHAR(36), lead_employee_id CHAR(36), effective_from DATE NOT NULL, effective_to DATE, allocation_percent_basis_points SMALLINT UNSIGNED NOT NULL, expected_weekly_minutes INT UNSIGNED NOT NULL, is_primary BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_assignment_start(employee_id,division_id,effective_from), KEY ix_assignment_effective(employee_id,effective_from,effective_to,is_active), CHECK(allocation_percent_basis_points <= 10000), CHECK(effective_to IS NULL OR effective_to >= effective_from), CONSTRAINT fk_assignments_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_assignments_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_assignments_team FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE RESTRICT, CONSTRAINT fk_assignments_lead FOREIGN KEY(lead_employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE scoped_grants (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, permission_id CHAR(36) NOT NULL, division_id CHAR(36), project_id CHAR(36), effective_from DATE NOT NULL, effective_to DATE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CHECK(effective_to IS NULL OR effective_to >= effective_from), KEY ix_scoped_grants_user_date(user_id,effective_from,effective_to), CONSTRAINT fk_grants_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_grants_permission FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE RESTRICT, CONSTRAINT fk_grants_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE policy_versions (id CHAR(36) PRIMARY KEY, policy_key VARCHAR(64) NOT NULL, version_number INT UNSIGNED NOT NULL, effective_from DATE NOT NULL, effective_to DATE, timezone VARCHAR(64) NOT NULL, required_active_minutes INT UNSIGNED NOT NULL, recognized_break_minutes INT UNSIGNED NOT NULL, scheduled_minutes INT UNSIGNED NOT NULL, overtime_limit_minutes INT UNSIGNED NOT NULL, configuration JSON NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_policy_version(policy_key,version_number), CHECK(effective_to IS NULL OR effective_to >= effective_from), CHECK(required_active_minutes + recognized_break_minutes = scheduled_minutes)) ENGINE=InnoDB;
CREATE TABLE work_policies (id CHAR(36) PRIMARY KEY, employee_id CHAR(36), division_id CHAR(36), policy_version_id CHAR(36) NOT NULL, effective_from DATE NOT NULL, effective_to DATE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CHECK(effective_to IS NULL OR effective_to >= effective_from), KEY ix_work_policy_employee_date(employee_id,effective_from,effective_to), CONSTRAINT fk_work_policy_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_work_policy_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_work_policy_version FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE holiday_calendars (id CHAR(36) PRIMARY KEY, division_id CHAR(36), name VARCHAR(160) NOT NULL, effective_from DATE NOT NULL, effective_to DATE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CHECK(effective_to IS NULL OR effective_to >= effective_from), CONSTRAINT fk_holiday_calendars_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE holidays (id CHAR(36) PRIMARY KEY, calendar_id CHAR(36) NOT NULL, holiday_date DATE NOT NULL, name VARCHAR(160) NOT NULL, portion ENUM('full_day','first_half','second_half') NOT NULL DEFAULT 'full_day', is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_holiday_calendar_date(calendar_id,holiday_date), CONSTRAINT fk_holidays_calendar FOREIGN KEY(calendar_id) REFERENCES holiday_calendars(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE projects (id CHAR(36) PRIMARY KEY, division_id CHAR(36) NOT NULL, project_code VARCHAR(64) NOT NULL, name VARCHAR(200) NOT NULL, status ENUM('draft','active','on_hold','closed') NOT NULL, manager_employee_id CHAR(36), estimated_minutes INT UNSIGNED, deadline DATE, priority VARCHAR(32), budget_amount DECIMAL(19,4), currency CHAR(3), client_name VARCHAR(200), notes TEXT, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_project_code(project_code), KEY ix_projects_division_status(division_id,status), CHECK((budget_amount IS NULL) = (currency IS NULL)), CONSTRAINT fk_projects_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_projects_manager FOREIGN KEY(manager_employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
ALTER TABLE scoped_grants ADD CONSTRAINT fk_grants_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT;
CREATE TABLE project_members (id CHAR(36) PRIMARY KEY, project_id CHAR(36) NOT NULL, employee_id CHAR(36) NOT NULL, effective_from DATE NOT NULL, effective_to DATE, allocation_percent_basis_points SMALLINT UNSIGNED, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_project_member_start(project_id,employee_id,effective_from), CHECK(effective_to IS NULL OR effective_to >= effective_from), CHECK(allocation_percent_basis_points IS NULL OR allocation_percent_basis_points <= 10000), CONSTRAINT fk_project_members_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT, CONSTRAINT fk_project_members_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE tasks (id CHAR(36) PRIMARY KEY, project_id CHAR(36) NOT NULL, parent_task_id CHAR(36), title VARCHAR(240) NOT NULL, description TEXT, status ENUM('backlog','todo','in_progress','blocked','done','cancelled') NOT NULL, priority VARCHAR(32), assignee_employee_id CHAR(36), estimated_minutes INT UNSIGNED, due_date DATE, completed_at DATETIME(6), is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_tasks_project_status(project_id,status,due_date), CONSTRAINT fk_tasks_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT, CONSTRAINT fk_tasks_parent FOREIGN KEY(parent_task_id) REFERENCES tasks(id) ON DELETE RESTRICT, CONSTRAINT fk_tasks_assignee FOREIGN KEY(assignee_employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE task_members (task_id CHAR(36) NOT NULL, employee_id CHAR(36) NOT NULL, PRIMARY KEY(task_id,employee_id), CONSTRAINT fk_task_members_task FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE RESTRICT, CONSTRAINT fk_task_members_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE task_checklist_items (id CHAR(36) PRIMARY KEY, task_id CHAR(36) NOT NULL, label VARCHAR(240) NOT NULL, position INT UNSIGNED NOT NULL, is_done BOOLEAN NOT NULL DEFAULT FALSE, completed_at DATETIME(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_checklist_position(task_id,position), CONSTRAINT fk_checklist_task FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE attachments (id CHAR(36) PRIMARY KEY, owner_type VARCHAR(64) NOT NULL, owner_id CHAR(36) NOT NULL, uploaded_by_user_id CHAR(36) NOT NULL, storage_key VARCHAR(512) NOT NULL, original_name VARCHAR(255) NOT NULL, media_type VARCHAR(127) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, sha256 CHAR(64) NOT NULL, scan_status ENUM('pending','clean','rejected','failed') NOT NULL DEFAULT 'pending', sensitivity VARCHAR(32) NOT NULL DEFAULT 'protected', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), deactivated_at DATETIME(6), UNIQUE KEY uq_attachments_storage_key(storage_key), KEY ix_attachments_owner(owner_type,owner_id), CONSTRAINT fk_attachments_user FOREIGN KEY(uploaded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE work_attachments (project_id CHAR(36), task_id CHAR(36), attachment_id CHAR(36) NOT NULL, UNIQUE KEY uq_work_attachment(attachment_id), CONSTRAINT fk_work_attachment_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT, CONSTRAINT fk_work_attachment_task FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE RESTRICT, CONSTRAINT fk_work_attachment_file FOREIGN KEY(attachment_id) REFERENCES attachments(id) ON DELETE RESTRICT, CHECK(project_id IS NOT NULL OR task_id IS NOT NULL)) ENGINE=InnoDB;

CREATE TABLE timesheet_periods (id CHAR(36) PRIMARY KEY, label VARCHAR(120) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status ENUM('open','pending_verification','verified','amended') NOT NULL DEFAULT 'open', policy_version_id CHAR(36) NOT NULL, verified_at DATETIME(6), verified_by_user_id CHAR(36), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_timesheet_period_range(start_date,end_date), CHECK(end_date >= start_date), KEY ix_period_status_date(status,start_date,end_date), CONSTRAINT fk_period_policy FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT, CONSTRAINT fk_period_verifier FOREIGN KEY(verified_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE time_entries (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, work_date DATE NOT NULL, division_id CHAR(36) NOT NULL, project_id CHAR(36), task_id CHAR(36), policy_version_id CHAR(36) NOT NULL, timezone VARCHAR(64) NOT NULL, entry_method ENUM('manual_clock','manual_duration','timer','calendar_draft') NOT NULL, work_location ENUM('office','wfh','client_site','field','other') NOT NULL, start_at_utc DATETIME(6), end_at_utc DATETIME(6), active_minutes INT UNSIGNED NOT NULL, work_description TEXT NOT NULL, completed_work TEXT NOT NULL, supporting_link VARCHAR(1024), overtime_reason TEXT, critical_explanation TEXT, status ENUM('draft','saved','amended') NOT NULL DEFAULT 'saved', is_active BOOLEAN NOT NULL DEFAULT TRUE, created_by_user_id CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_time_employee_date(employee_id,work_date,start_at_utc,end_at_utc), KEY ix_time_division_date(division_id,work_date), KEY ix_time_project_date(project_id,work_date), KEY ix_time_task_date(task_id,work_date), CHECK(end_at_utc IS NULL OR start_at_utc IS NULL OR end_at_utc > start_at_utc), CONSTRAINT fk_time_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_time_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_time_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT, CONSTRAINT fk_time_task FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE RESTRICT, CONSTRAINT fk_time_policy FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT, CONSTRAINT fk_time_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE timer_sessions (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, division_id CHAR(36) NOT NULL, project_id CHAR(36), task_id CHAR(36), work_location VARCHAR(32) NOT NULL, started_at_utc DATETIME(6) NOT NULL, stopped_at_utc DATETIME(6), cancelled_at_utc DATETIME(6), timezone VARCHAR(64) NOT NULL, created_by_user_id CHAR(36) NOT NULL, running_employee_id CHAR(36) GENERATED ALWAYS AS (IF(stopped_at_utc IS NULL AND cancelled_at_utc IS NULL,employee_id,NULL)) STORED, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_one_running_timer(running_employee_id), KEY ix_timer_employee_start(employee_id,started_at_utc), CONSTRAINT fk_timer_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_timer_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_timer_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT, CONSTRAINT fk_timer_task FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE RESTRICT, CONSTRAINT fk_timer_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE daily_breaks (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, work_date DATE NOT NULL, minutes INT UNSIGNED NOT NULL, source ENUM('policy','override') NOT NULL, reason TEXT, policy_version_id CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_daily_break(employee_id,work_date), CONSTRAINT fk_daily_break_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_daily_break_policy FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE daily_summaries (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, work_date DATE NOT NULL, active_minutes INT UNSIGNED NOT NULL, break_minutes INT UNSIGNED NOT NULL, total_minutes INT UNSIGNED NOT NULL, required_active_minutes INT UNSIGNED NOT NULL, required_break_minutes INT UNSIGNED NOT NULL, classification ENUM('missing','under_time','complete','overtime','critical','not_required') NOT NULL, timezone VARCHAR(64) NOT NULL, policy_version_id CHAR(36) NOT NULL, recalculated_at DATETIME(6) NOT NULL, source_version INT UNSIGNED NOT NULL, UNIQUE KEY uq_daily_summary(employee_id,work_date), KEY ix_summary_date_class(work_date,classification), CHECK(total_minutes = active_minutes + break_minutes), CONSTRAINT fk_summary_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_summary_policy FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE period_verifications (id CHAR(36) PRIMARY KEY, period_id CHAR(36) NOT NULL, verified_by_user_id CHAR(36) NOT NULL, verified_at DATETIME(6) NOT NULL, note TEXT, policy_version_id CHAR(36) NOT NULL, snapshot_hash CHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), KEY ix_verification_period(period_id,verified_at), CONSTRAINT fk_verification_period FOREIGN KEY(period_id) REFERENCES timesheet_periods(id) ON DELETE RESTRICT, CONSTRAINT fk_verification_user FOREIGN KEY(verified_by_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_verification_policy FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE period_unlock_requests (id CHAR(36) PRIMARY KEY, period_id CHAR(36) NOT NULL, requested_by_user_id CHAR(36) NOT NULL, reason TEXT NOT NULL, status ENUM('requested','approved','rejected','completed') NOT NULL, decided_by_user_id CHAR(36), decided_at DATETIME(6), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CONSTRAINT fk_unlock_period FOREIGN KEY(period_id) REFERENCES timesheet_periods(id) ON DELETE RESTRICT, CONSTRAINT fk_unlock_requester FOREIGN KEY(requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_unlock_decider FOREIGN KEY(decided_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE timesheet_amendments (id CHAR(36) PRIMARY KEY, period_id CHAR(36) NOT NULL, record_type VARCHAR(64) NOT NULL, record_id CHAR(36) NOT NULL, reason TEXT NOT NULL, before_values JSON NOT NULL, after_values JSON NOT NULL, amended_by_user_id CHAR(36) NOT NULL, amended_at DATETIME(6) NOT NULL, correlation_id CHAR(36) NOT NULL, KEY ix_amendment_period_record(period_id,record_type,record_id), CONSTRAINT fk_amendment_period FOREIGN KEY(period_id) REFERENCES timesheet_periods(id) ON DELETE RESTRICT, CONSTRAINT fk_amendment_user FOREIGN KEY(amended_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE wfh_requests (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, division_id CHAR(36) NOT NULL, wfh_date DATE NOT NULL, portion ENUM('full_day','first_half','second_half') NOT NULL, reason TEXT NOT NULL, planned_tasks TEXT NOT NULL, contact_availability VARCHAR(255) NOT NULL, status ENUM('draft','submitted','approved','rejected','information_requested','cancelled') NOT NULL, decided_by_user_id CHAR(36), decision_comment TEXT, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_wfh_employee_date(employee_id,wfh_date), CONSTRAINT fk_wfh_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_wfh_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_wfh_decider FOREIGN KEY(decided_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE leave_types (id CHAR(36) PRIMARY KEY, type_key VARCHAR(64) NOT NULL, name VARCHAR(120) NOT NULL, is_paid BOOLEAN NOT NULL, requires_attachment BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE KEY uq_leave_type_key(type_key)) ENGINE=InnoDB;
CREATE TABLE leave_balances (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, leave_type_id CHAR(36) NOT NULL, year SMALLINT UNSIGNED NOT NULL, entitled_minutes INT UNSIGNED NOT NULL, used_minutes INT UNSIGNED NOT NULL DEFAULT 0, reserved_minutes INT UNSIGNED NOT NULL DEFAULT 0, version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_leave_balance(employee_id,leave_type_id,year), CHECK(used_minutes + reserved_minutes <= entitled_minutes), CONSTRAINT fk_leave_balance_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_leave_balance_type FOREIGN KEY(leave_type_id) REFERENCES leave_types(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE leave_requests (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, leave_type_id CHAR(36) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, portion ENUM('full_day','first_half','second_half') NOT NULL, requested_minutes INT UNSIGNED NOT NULL, reason TEXT NOT NULL, status ENUM('draft','submitted','approved','rejected','information_requested','cancelled') NOT NULL, decided_by_user_id CHAR(36), decision_comment TEXT, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CHECK(end_date >= start_date), KEY ix_leave_employee_date(employee_id,start_date,end_date), CONSTRAINT fk_leave_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_leave_type FOREIGN KEY(leave_type_id) REFERENCES leave_types(id) ON DELETE RESTRICT, CONSTRAINT fk_leave_decider FOREIGN KEY(decided_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE attendance_days (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, work_date DATE NOT NULL, status VARCHAR(48) NOT NULL, required_minutes INT UNSIGNED NOT NULL, worked_minutes INT UNSIGNED NOT NULL, source_version INT UNSIGNED NOT NULL, recalculated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_attendance_day(employee_id,work_date), KEY ix_attendance_date_status(work_date,status), CONSTRAINT fk_attendance_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE general_remarks (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, author_user_id CHAR(36) NOT NULL, message TEXT NOT NULL, related_type VARCHAR(64), related_id CHAR(36), is_correction_request BOOLEAN NOT NULL DEFAULT FALSE, requested_changes TEXT, status ENUM('open','responded','resolved') NOT NULL DEFAULT 'open', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_remarks_employee_status(employee_id,status,created_at), CONSTRAINT fk_remarks_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_remarks_author FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE evaluation_periods (id CHAR(36) PRIMARY KEY, label VARCHAR(120) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status ENUM('draft','open','review','published','closed') NOT NULL, weights JSON NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CHECK(end_date >= start_date)) ENGINE=InnoDB;
CREATE TABLE evaluations (id CHAR(36) PRIMARY KEY, period_id CHAR(36) NOT NULL, employee_id CHAR(36) NOT NULL, reviewer_employee_id CHAR(36) NOT NULL, status ENUM('draft','self_submitted','review_submitted','published') NOT NULL, final_score DECIMAL(7,4), published_at DATETIME(6), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_evaluation(period_id,employee_id), CONSTRAINT fk_evaluation_period FOREIGN KEY(period_id) REFERENCES evaluation_periods(id) ON DELETE RESTRICT, CONSTRAINT fk_evaluation_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_evaluation_reviewer FOREIGN KEY(reviewer_employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE evaluation_responses (id CHAR(36) PRIMARY KEY, evaluation_id CHAR(36) NOT NULL, respondent_employee_id CHAR(36) NOT NULL, response_type ENUM('self','reviewer') NOT NULL, answers JSON NOT NULL, summary TEXT, submitted_at DATETIME(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_evaluation_response(evaluation_id,response_type), CONSTRAINT fk_evaluation_response_evaluation FOREIGN KEY(evaluation_id) REFERENCES evaluations(id) ON DELETE RESTRICT, CONSTRAINT fk_evaluation_response_employee FOREIGN KEY(respondent_employee_id) REFERENCES employees(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE evaluation_scores (id CHAR(36) PRIMARY KEY, evaluation_id CHAR(36) NOT NULL, criterion_key VARCHAR(64) NOT NULL, score_basis_points INT UNSIGNED NOT NULL, weight_basis_points INT UNSIGNED NOT NULL, weighted_score DECIMAL(11,4) NOT NULL, UNIQUE KEY uq_evaluation_score(evaluation_id,criterion_key), CHECK(score_basis_points <= 10000), CHECK(weight_basis_points <= 10000), CONSTRAINT fk_evaluation_score_evaluation FOREIGN KEY(evaluation_id) REFERENCES evaluations(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE workload_allocations (id CHAR(36) PRIMARY KEY, employee_id CHAR(36) NOT NULL, division_id CHAR(36) NOT NULL, project_id CHAR(36), week_start_date DATE NOT NULL, planned_minutes INT UNSIGNED NOT NULL, capacity_minutes INT UNSIGNED NOT NULL, allocation_basis_points SMALLINT UNSIGNED NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_workload(employee_id,division_id,project_id,week_start_date), CHECK(allocation_basis_points <= 10000), CONSTRAINT fk_workload_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_workload_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_workload_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE cost_rates (id CHAR(36) PRIMARY KEY, employee_id CHAR(36), division_id CHAR(36), project_id CHAR(36), rate_amount DECIMAL(19,4) NOT NULL, currency CHAR(3) NOT NULL, rate_unit ENUM('hour','day','month') NOT NULL, effective_from DATE NOT NULL, effective_to DATE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CHECK(rate_amount >= 0), CHECK(effective_to IS NULL OR effective_to >= effective_from), KEY ix_cost_rate_effective(employee_id,division_id,project_id,effective_from,effective_to), CONSTRAINT fk_cost_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT fk_cost_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_cost_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE budgets (id CHAR(36) PRIMARY KEY, division_id CHAR(36), project_id CHAR(36), period_start DATE NOT NULL, period_end DATE NOT NULL, amount DECIMAL(19,4) NOT NULL, currency CHAR(3) NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, CHECK(period_end >= period_start), CHECK(amount >= 0), CONSTRAINT fk_budget_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_budget_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE payroll_periods (id CHAR(36) PRIMARY KEY, label VARCHAR(120) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, timesheet_period_id CHAR(36) NOT NULL, status ENUM('open','ready','exported','closed') NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_payroll_range(start_date,end_date), CHECK(end_date >= start_date), CONSTRAINT fk_payroll_timesheet_period FOREIGN KEY(timesheet_period_id) REFERENCES timesheet_periods(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE report_definitions (id CHAR(36) PRIMARY KEY, report_key VARCHAR(100) NOT NULL, name VARCHAR(160) NOT NULL, module VARCHAR(64) NOT NULL, required_permission VARCHAR(128), configuration JSON NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, version INT UNSIGNED NOT NULL DEFAULT 1, UNIQUE KEY uq_report_key(report_key)) ENGINE=InnoDB;
CREATE TABLE export_jobs (id CHAR(36) PRIMARY KEY, requested_by_user_id CHAR(36) NOT NULL, report_definition_id CHAR(36) NOT NULL, format ENUM('xlsx','csv','pdf','print') NOT NULL, filters JSON NOT NULL, timezone VARCHAR(64) NOT NULL, policy_version_id CHAR(36), state ENUM('queued','processing','ready','failed','cancelled','expired') NOT NULL, requested_at DATETIME(6) NOT NULL, completed_at DATETIME(6), expires_at DATETIME(6), failure_code VARCHAR(64), idempotency_key VARCHAR(128) NOT NULL, UNIQUE KEY uq_export_idempotency(requested_by_user_id,idempotency_key), KEY ix_export_user_state(requested_by_user_id,state,requested_at), CONSTRAINT fk_export_user FOREIGN KEY(requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_export_report FOREIGN KEY(report_definition_id) REFERENCES report_definitions(id) ON DELETE RESTRICT, CONSTRAINT fk_export_policy FOREIGN KEY(policy_version_id) REFERENCES policy_versions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE export_artifacts (id CHAR(36) PRIMARY KEY, export_job_id CHAR(36) NOT NULL, storage_key VARCHAR(512) NOT NULL, sha256 CHAR(64) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, media_type VARCHAR(127) NOT NULL, expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_export_artifact_job(export_job_id), UNIQUE KEY uq_export_storage_key(storage_key), CONSTRAINT fk_export_artifact_job FOREIGN KEY(export_job_id) REFERENCES export_jobs(id) ON DELETE RESTRICT) ENGINE=InnoDB;

CREATE TABLE notifications (id CHAR(36) PRIMARY KEY, recipient_user_id CHAR(36) NOT NULL, notification_type VARCHAR(64) NOT NULL, safe_payload JSON NOT NULL, related_type VARCHAR(64), related_id CHAR(36), deduplication_key VARCHAR(191), read_at DATETIME(6), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_notification_dedupe(recipient_user_id,deduplication_key), KEY ix_notification_unread(recipient_user_id,read_at,created_at), CONSTRAINT fk_notification_user FOREIGN KEY(recipient_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE delivery_attempts (id CHAR(36) PRIMARY KEY, notification_id CHAR(36), channel VARCHAR(32) NOT NULL, provider_message_id VARCHAR(191), state VARCHAR(32) NOT NULL, attempt_number INT UNSIGNED NOT NULL, next_attempt_at DATETIME(6), safe_error_code VARCHAR(64), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), KEY ix_delivery_retry(state,next_attempt_at), CONSTRAINT fk_delivery_notification FOREIGN KEY(notification_id) REFERENCES notifications(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE documents (id CHAR(36) PRIMARY KEY, title VARCHAR(240) NOT NULL, scope_type ENUM('company','division','project') NOT NULL, division_id CHAR(36), project_id CHAR(36), sensitivity VARCHAR(32) NOT NULL DEFAULT 'protected', created_by_user_id CHAR(36) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_documents_scope(scope_type,division_id,project_id,is_active), CONSTRAINT fk_document_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT, CONSTRAINT fk_document_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT, CONSTRAINT fk_document_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE document_versions (id CHAR(36) PRIMARY KEY, document_id CHAR(36) NOT NULL, version_number INT UNSIGNED NOT NULL, attachment_id CHAR(36) NOT NULL, created_by_user_id CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_document_version(document_id,version_number), CONSTRAINT fk_document_version_document FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE RESTRICT, CONSTRAINT fk_document_version_attachment FOREIGN KEY(attachment_id) REFERENCES attachments(id) ON DELETE RESTRICT, CONSTRAINT fk_document_version_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE messages (id CHAR(36) PRIMARY KEY, sender_user_id CHAR(36) NOT NULL, scope_type ENUM('division','project','direct') NOT NULL, scope_id CHAR(36) NOT NULL, body TEXT NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), edited_at DATETIME(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_messages_scope(scope_type,scope_id,created_at), CONSTRAINT fk_messages_sender FOREIGN KEY(sender_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE comments (id CHAR(36) PRIMARY KEY, author_user_id CHAR(36) NOT NULL, owner_type VARCHAR(64) NOT NULL, owner_id CHAR(36) NOT NULL, body TEXT NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), edited_at DATETIME(6), version INT UNSIGNED NOT NULL DEFAULT 1, KEY ix_comments_owner(owner_type,owner_id,created_at), CONSTRAINT fk_comments_author FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE announcements (id CHAR(36) PRIMARY KEY, author_user_id CHAR(36) NOT NULL, scope_type ENUM('company','division','project') NOT NULL, scope_id CHAR(36), title VARCHAR(240) NOT NULL, body TEXT NOT NULL, published_at DATETIME(6), expires_at DATETIME(6), is_pinned BOOLEAN NOT NULL DEFAULT FALSE, version INT UNSIGNED NOT NULL DEFAULT 1, CONSTRAINT fk_announcements_author FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE search_metadata (id CHAR(36) PRIMARY KEY, resource_type VARCHAR(64) NOT NULL, resource_id CHAR(36) NOT NULL, title VARCHAR(512) NOT NULL, safe_text TEXT, scope_json JSON NOT NULL, source_version INT UNSIGNED NOT NULL, indexed_at DATETIME(6) NOT NULL, UNIQUE KEY uq_search_resource(resource_type,resource_id), FULLTEXT KEY ft_search_text(title,safe_text)) ENGINE=InnoDB;

CREATE TABLE integration_connections (id CHAR(36) PRIMARY KEY, provider_key VARCHAR(64) NOT NULL, owner_user_id CHAR(36), division_id CHAR(36), encrypted_credential_ref VARCHAR(512) NOT NULL, status VARCHAR(32) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CONSTRAINT fk_integration_owner FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_integration_division FOREIGN KEY(division_id) REFERENCES divisions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE integration_sync_cursors (connection_id CHAR(36) PRIMARY KEY, cursor_value TEXT, last_synced_at DATETIME(6), version INT UNSIGNED NOT NULL DEFAULT 1, CONSTRAINT fk_sync_cursor_connection FOREIGN KEY(connection_id) REFERENCES integration_connections(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE webhook_endpoints (id CHAR(36) PRIMARY KEY, owner_user_id CHAR(36) NOT NULL, target_url VARCHAR(1024) NOT NULL, secret_ref VARCHAR(512) NOT NULL, subscribed_events JSON NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), version INT UNSIGNED NOT NULL DEFAULT 1, CONSTRAINT fk_webhook_owner FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE webhook_deliveries (id CHAR(36) PRIMARY KEY, endpoint_id CHAR(36) NOT NULL, event_id CHAR(36) NOT NULL, state VARCHAR(32) NOT NULL, attempt_count INT UNSIGNED NOT NULL DEFAULT 0, next_attempt_at DATETIME(6), response_code SMALLINT UNSIGNED, safe_error_code VARCHAR(64), created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_webhook_event(endpoint_id,event_id), KEY ix_webhook_retry(state,next_attempt_at), CONSTRAINT fk_webhook_endpoint FOREIGN KEY(endpoint_id) REFERENCES webhook_endpoints(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE idempotency_records (id CHAR(36) PRIMARY KEY, actor_user_id CHAR(36) NOT NULL, operation_key VARCHAR(100) NOT NULL, idempotency_key VARCHAR(128) NOT NULL, request_hash CHAR(64) NOT NULL, response_status VARCHAR(32), response_body JSON, expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_idempotency(actor_user_id,operation_key,idempotency_key), KEY ix_idempotency_expiry(expires_at), CONSTRAINT fk_idempotency_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE job_records (id CHAR(36) PRIMARY KEY, queue_name VARCHAR(100) NOT NULL, job_name VARCHAR(100) NOT NULL, state VARCHAR(32) NOT NULL, payload_ref VARCHAR(512), idempotency_key VARCHAR(191) NOT NULL, attempt_count INT UNSIGNED NOT NULL DEFAULT 0, available_at DATETIME(6) NOT NULL, completed_at DATETIME(6), safe_error_code VARCHAR(64), correlation_id CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_job_idempotency(queue_name,idempotency_key), KEY ix_job_claim(queue_name,state,available_at)) ENGINE=InnoDB;
CREATE TABLE audit_events (sequence_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id CHAR(36) NOT NULL, actor_user_id CHAR(36), impersonator_user_id CHAR(36), action VARCHAR(128) NOT NULL, resource_type VARCHAR(64) NOT NULL, resource_id CHAR(36), scope_json JSON NOT NULL, reason TEXT, correlation_id CHAR(36) NOT NULL, before_protected JSON, after_protected JSON, occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_audit_event_id(event_id), KEY ix_audit_resource(resource_type,resource_id,occurred_at), KEY ix_audit_actor(actor_user_id,occurred_at), KEY ix_audit_correlation(correlation_id), CONSTRAINT fk_audit_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_audit_impersonator FOREIGN KEY(impersonator_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB;

