import 'server-only';
import type { Pool, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import type { EmployeeDivisionViewService, EmployeeRemarkDetailView, EmployeeRemarkViewService, EmployeeTaskDetailView, EmployeeTaskViewService } from '@/contracts/employee-views';
import type { DivisionRef, EmployeeRef, RemarkSummaryView, TaskSummaryView } from '@/contracts/view-models';
import type { Result } from '@/contracts/results';
import { success } from '@/contracts/results';
import { formatDate, formatDurationDelta } from '@/lib/format';
import { REMARK_STATE_LABEL, TASK_STATUS_LABEL, toDurationView } from '@/lib/status';
import { AuthenticationService } from '@/server/authentication/service';
import { MysqlAuthenticationStore } from '@/server/authentication/mysql-store';
import { loadActorPolicyContext } from '@/server/authorization/mysql-context';

type Row=RowDataPacket&Record<string,unknown>;
const absent=(resource:string):Result<never>=>({status:'not_found',code:'NOT_FOUND',message:`${resource} was not found.`,resource});
const stringDate=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
const employee=(row:Row,prefix=''):EmployeeRef=>({id:String(row[`${prefix}id`]),employeeCode:String(row[`${prefix}employee_code`]),fullName:String(row[`${prefix}display_name`]),avatarUrl:row[`${prefix}image_url`]?String(row[`${prefix}image_url`]):null,designation:row[`${prefix}job_title`]?String(row[`${prefix}job_title`]):null});
const division=(row:Row):DivisionRef=>({id:String(row.division_id),name:String(row.division_name),code:String(row.division_code),isRestricted:Boolean(row.division_restricted)});

export class BackendEmployeeViews {
  private readonly auth:AuthenticationService;
  constructor(private readonly pool:Pool,private readonly sessionToken:string){this.auth=new AuthenticationService(new MysqlAuthenticationStore(pool));}
  private async actor(){const session=await this.auth.validateSession(this.sessionToken);return session.status==='success'?loadActorPolicyContext(this.pool,session.data.userId,new Date().toISOString().slice(0,10)):null;}
  private async mayRead(employeeId:string){const actor=await this.actor();return Boolean(actor&&(actor.employeeId===employeeId||actor.employeeIds.has(employeeId)||actor.roles.includes('super_admin')||actor.roles.includes('hr_manager')));}
  private async taskRows(employeeId:string,taskId?:string){const [rows]=await this.pool.execute<Row[]>(`SELECT t.id,t.title,t.description,t.status,t.priority,t.due_date,t.estimated_minutes,t.review_state,t.review_note,
    p.id project_id,p.name project_name,p.project_code,p.division_id,d.name division_name,d.division_key division_code,d.is_government division_restricted,
    e.id assignee_id,e.employee_code assignee_employee_code,e.display_name assignee_display_name,e.job_title assignee_job_title,u.image_url assignee_image_url,
    COALESCE((SELECT SUM(te.active_minutes) FROM time_entries te WHERE te.task_id=t.id AND te.is_active=TRUE AND te.status<>'draft'),0) actual_minutes
    FROM tasks t JOIN projects p ON p.id=t.project_id JOIN divisions d ON d.id=p.division_id LEFT JOIN employees e ON e.id=t.assignee_employee_id LEFT JOIN users u ON u.id=e.user_id
    WHERE t.is_active=TRUE AND (t.assignee_employee_id=? OR EXISTS(SELECT 1 FROM task_members tm WHERE tm.task_id=t.id AND tm.employee_id=?)) ${taskId?'AND t.id=?':''}`,taskId?[employeeId,employeeId,taskId]:[employeeId,employeeId]);return rows;}
  private async taskSummary(row:Row):Promise<TaskSummaryView>{const id=String(row.id),actual=Number(row.actual_minutes),estimated=Number(row.estimated_minutes??0),due=row.due_date?stringDate(row.due_date):null;const [daily]=await this.pool.execute<Row[]>('SELECT work_date,SUM(active_minutes) minutes,GROUP_CONCAT(id ORDER BY id) ids FROM time_entries WHERE task_id=? AND is_active=TRUE AND status<>\'draft\' GROUP BY work_date ORDER BY work_date',[id]);const reviewState=String(row.review_state??'not_required') as TaskSummaryView['review']['state'];const reviewLabel={not_required:'No review required',pending_review:'Awaiting review',approved:'Approved',rejected:'Not approved'}[reviewState];const reviewDetail={not_required:'Assigned by your Team Lead.',pending_review:'Your Team Lead must review this task before it can receive work.',approved:'Your Team Lead approved this task.',rejected:'This task cannot receive work.'}[reviewState];return{id,title:String(row.title),project:{id:String(row.project_id),name:String(row.project_name),code:String(row.project_code),divisionId:String(row.division_id)},division:division(row),assignee:row.assignee_id?employee(row,'assignee_'):null,status:String(row.status) as TaskSummaryView['status'],statusLabel:TASK_STATUS_LABEL[String(row.status) as keyof typeof TASK_STATUS_LABEL],priority:String(row.priority??'medium') as TaskSummaryView['priority'],dueDate:due,dueDateLabel:due?formatDate(due):null,isOverdue:Boolean(due&&due<new Date().toISOString().slice(0,10)&&row.status!=='completed'),estimated:toDurationView(estimated),actual:toDurationView(actual),variance:{minutes:actual-estimated,label:formatDurationDelta(actual-estimated)},dailyActuals:daily.map(day=>({workDate:stringDate(day.work_date),workDateLabel:formatDate(stringDate(day.work_date)),actual:toDurationView(Number(day.minutes)),workLogIds:String(day.ids??'').split(',').filter(Boolean)})),review:{state:reviewState,label:reviewLabel,detail:reviewDetail,blocksTimeEntry:reviewState==='pending_review'||reviewState==='rejected',reviewerName:null,reviewedAtLabel:null,note:row.review_note?String(row.review_note):null},variancePercent:estimated?Math.round((actual-estimated)*100/estimated):null,href:`/tasks/${id}`};}
  async taskGet(taskId:string,employeeId?:string):Promise<Result<EmployeeTaskDetailView>>{const actor=await this.actor();const scopedEmployee=employeeId||actor?.employeeId;if(!actor||!scopedEmployee||!await this.mayRead(scopedEmployee))return absent('Task');const row=(await this.taskRows(scopedEmployee,taskId))[0];if(!row)return absent('Task');const [checklist]=await this.pool.execute<Row[]>('SELECT id,task_id,label,position,is_done FROM task_checklist_items WHERE task_id=? ORDER BY position',[taskId]);const [members]=await this.pool.execute<Row[]>('SELECT e.id,e.employee_code,e.display_name,e.job_title,u.image_url FROM task_members tm JOIN employees e ON e.id=tm.employee_id JOIN users u ON u.id=e.user_id WHERE tm.task_id=?',[taskId]);const [entries]=await this.pool.execute<Row[]>(`SELECT te.id,te.work_date,te.active_minutes,te.completed_work,d.id division_id,d.name division_name,d.division_key division_code,d.is_government division_restricted FROM time_entries te JOIN divisions d ON d.id=te.division_id WHERE te.task_id=? AND te.is_active=TRUE AND te.status<>'draft' ORDER BY te.work_date DESC`,[taskId]);return success({summary:await this.taskSummary(row),description:row.description?String(row.description):null,checklist:checklist.map(item=>({id:String(item.id),taskId:String(item.task_id),label:String(item.label),order:Number(item.position),isDone:Boolean(item.is_done)})),supportingMembers:members.map(item=>employee(item)),entries:entries.map(item=>({id:String(item.id),workDate:stringDate(item.work_date),workDateLabel:formatDate(stringDate(item.work_date)),duration:toDurationView(Number(item.active_minutes)),completedWork:String(item.completed_work),division:division(item)}))});}
  async setChecklistItem(itemId:string,isDone:boolean){const actor=await this.actor();if(!actor?.employeeId)return absent('Checklist item');const [result]=await this.pool.execute<ResultSetHeader>(`UPDATE task_checklist_items ci JOIN tasks t ON t.id=ci.task_id LEFT JOIN task_members tm ON tm.task_id=t.id SET ci.is_done=?,ci.completed_at=?,ci.version=ci.version+1 WHERE ci.id=? AND (t.assignee_employee_id=? OR tm.employee_id=?)`,[isDone,isDone?new Date():null,itemId,actor.employeeId,actor.employeeId]);return result.affectedRows?success(undefined):absent('Checklist item');}

  private async remarkSummary(row:Row):Promise<RemarkSummaryView>{const relatedType=String(row.related_type??''),relatedId=row.related_id?String(row.related_id):null,date=row.related_work_date?stringDate(row.related_work_date):null;return{id:String(row.id),author:employee(row,'author_'),employee:employee(row,'employee_'),message:String(row.message),createdAtLabel:formatDate(stringDate(row.created_at)),state:String(row.status) as RemarkSummaryView['state'],stateLabel:REMARK_STATE_LABEL[String(row.status) as keyof typeof REMARK_STATE_LABEL],isCorrectionRequest:Boolean(row.is_correction_request),relatedLabel:relatedType==='time_entry'?(date?`Work log · ${formatDate(date)}`:'Work log'):relatedType==='task'?'Task':null,relatedHref:relatedType==='time_entry'&&date?`/timesheets/${date}${relatedId?`?workLog=${relatedId}`:''}`:relatedType==='task'&&relatedId?`/tasks/${relatedId}`:null,responseCount:(Array.isArray(row.responses_json)?row.responses_json:JSON.parse(String(row.responses_json??'[]'))).length,href:`/remarks/${String(row.id)}`};}
  private async remarkRows(employeeId?:string,id?:string){const values:string[]=[];let where='1=1';if(employeeId){where+=' AND r.employee_id=?';values.push(employeeId);}if(id){where+=' AND r.id=?';values.push(id);}const [rows]=await this.pool.execute<Row[]>(`SELECT r.*,ae.id author_id,ae.employee_code author_employee_code,ae.display_name author_display_name,ae.job_title author_job_title,au.image_url author_image_url,e.id employee_id,e.employee_code employee_employee_code,e.display_name employee_display_name,e.job_title employee_job_title,eu.image_url employee_image_url FROM general_remarks r JOIN users au ON au.id=r.author_user_id JOIN employees ae ON ae.user_id=au.id JOIN employees e ON e.id=r.employee_id JOIN users eu ON eu.id=e.user_id WHERE ${where} ORDER BY r.created_at DESC`,values);return rows;}
  async remarkList(employeeId:string):Promise<Result<readonly RemarkSummaryView[]>>{if(!await this.mayRead(employeeId))return absent('Remarks');return success(await Promise.all((await this.remarkRows(employeeId)).map(row=>this.remarkSummary(row))));}
  async remarkGet(remarkId:string):Promise<Result<EmployeeRemarkDetailView>>{const row=(await this.remarkRows(undefined,remarkId))[0];if(!row||!await this.mayRead(String(row.employee_id)))return absent('Remark');const responses=Array.isArray(row.responses_json)?row.responses_json:JSON.parse(String(row.responses_json??'[]'));const mapped=[];for(const value of responses as Record<string,unknown>[]){const [authors]=await this.pool.execute<Row[]>('SELECT e.id,e.employee_code,e.display_name,e.job_title,u.image_url FROM employees e JOIN users u ON u.id=e.user_id WHERE e.id=?',[String(value.authorEmployeeId??'')]);if(authors[0])mapped.push({id:String(value.id),author:employee(authors[0]),message:String(value.message),createdAtLabel:formatDate(stringDate(value.createdAt))});}return success({summary:await this.remarkSummary(row),requestedChanges:row.requested_changes?String(row.requested_changes):null,responses:mapped});}
  async respond(remarkId:string,message:string,employeeId:string){const actor=await this.actor();if(!actor||actor.employeeId!==employeeId||!message.trim())return absent('Remark');const rows=await this.remarkRows(employeeId,remarkId);if(!rows[0])return absent('Remark');const responses=Array.isArray(rows[0].responses_json)?rows[0].responses_json:JSON.parse(String(rows[0].responses_json??'[]'));responses.push({id:crypto.randomUUID(),authorEmployeeId:employeeId,message:message.trim(),createdAt:new Date().toISOString()});await this.pool.execute("UPDATE general_remarks SET status='responded',responses_json=?,version=version+1 WHERE id=? AND employee_id=?",[JSON.stringify(responses),remarkId,employeeId]);return success(undefined);}

  async listTasks(employeeId:string){if(!await this.mayRead(employeeId))return absent('Tasks');return success(await Promise.all((await this.taskRows(employeeId)).map(row=>this.taskSummary(row))));}
  async listDivisions(employeeId:string){if(!await this.mayRead(employeeId))return absent('Divisions');const [rows]=await this.pool.execute<Row[]>(`SELECT a.id,a.effective_from,a.effective_to,a.allocation_percent_basis_points,a.expected_weekly_minutes,a.is_primary,a.is_temporary,a.is_active,d.id division_id,d.name division_name,d.division_key division_code,d.is_government division_restricted,le.id lead_id,le.employee_code lead_employee_code,le.display_name lead_display_name,le.job_title lead_job_title,lu.image_url lead_image_url FROM employee_division_assignments a JOIN divisions d ON d.id=a.division_id LEFT JOIN departments dept ON dept.id=a.department_id AND dept.is_active=TRUE LEFT JOIN department_lead_assignments dla ON dla.department_id=dept.id AND dla.effective_from<=CURRENT_DATE AND (dla.effective_to IS NULL OR dla.effective_to>=CURRENT_DATE) LEFT JOIN employees le ON le.id=COALESCE(dla.lead_employee_id,a.lead_employee_id) LEFT JOIN users lu ON lu.id=le.user_id WHERE a.employee_id=? ORDER BY a.is_active DESC,a.effective_from DESC`,[employeeId]);const today=new Date().toISOString().slice(0,10);const assignments=rows.map(row=>{const from=stringDate(row.effective_from),to=row.effective_to?stringDate(row.effective_to):null;return{id:String(row.id),division:division(row),teamLead:row.lead_id?employee(row,'lead_'):null,isPrimary:Boolean(row.is_primary),allocationPercent:Number(row.allocation_percent_basis_points)/100,expectedWeekly:toDurationView(Number(row.expected_weekly_minutes)),startDateLabel:formatDate(from),endDateLabel:to?formatDate(to):null,isTemporary:Boolean(row.is_temporary),isActive:Boolean(row.is_active),isEffectiveToday:Boolean(row.is_active)&&from<=today&&(!to||to>=today)};});return success({assignments,totalAllocation:assignments.filter(a=>a.isEffectiveToday).reduce((sum,a)=>sum+a.allocationPercent,0)});}
}

export function employeeTaskService(service:BackendEmployeeViews):EmployeeTaskViewService{return{listForEmployee:(id)=>service.listTasks(id),getById:(...args)=>service.taskGet(...args),setChecklistItem:(...args)=>service.setChecklistItem(...args)};}
export function employeeRemarkService(service:BackendEmployeeViews):EmployeeRemarkViewService{return{listForEmployee:(id)=>service.remarkList(id),getById:(...args)=>service.remarkGet(...args),respond:(...args)=>service.respond(...args)};}
export function employeeDivisionService(service:BackendEmployeeViews):EmployeeDivisionViewService{return{listForEmployee:(id)=>service.listDivisions(id)};}
