import { createHash, randomUUID } from 'node:crypto';
import type { Pool, PoolConnection, RowDataPacket, ResultSetHeader } from 'mysql2/promise';
import type { DailySummary, GeneralRemark, WorkPolicy, Project, Task, Division } from '@/contracts/domain';
import type { Result } from '@/contracts/results';
import { hasPermission, type ActorPolicyContext } from '@/server/authorization/policy';
import { redactProtected } from '@/server/security/redaction';
import type { DayContext, StoredEntry, StoredPeriod, StoredTimer, TimeAudit, TimeRepository } from './ports';
type Row = RowDataPacket & Record<string, unknown>;
const json = <T>(value: unknown, fallback: T): T => value == null ? fallback : typeof value === 'string' ? JSON.parse(value) as T : value as T;
const iso = (value: unknown): string => value instanceof Date ? value.toISOString() : String(value).replace(' ', 'T') + (String(value).includes('T') ? '' : 'Z');
const date = (value: unknown): string => value instanceof Date ? value.toISOString().slice(0, 10) : String(value).slice(0, 10);
const sqlDate = (value: string | null) => value ? new Date(value) : null;
const provenance = (r: Row) => ({ createdAt: iso(r.created_at), updatedAt: iso(r.updated_at ?? r.created_at), createdBy: { userId: String(r.created_by_user_id ?? ''), displayName: 'Employee' }, updatedBy: { userId: String(r.updated_by_user_id ?? r.created_by_user_id ?? ''), displayName: 'Employee' } });
export class MysqlTimeRepository implements TimeRepository {
    constructor(private readonly pool: Pool, private readonly connection?: PoolConnection) { }
    private get db() { return this.connection ?? this.pool; }
    async rows(sql: string, values: (string | number | boolean | null | Date)[] = []): Promise<Row[]> { const [rows] = await this.db.execute<Row[]>(sql, values); return rows; }
    async transaction<T>(work: (tx: TimeRepository) => Promise<Result<T>>): Promise<Result<T>> {
        if (this.connection)
            return work(this);
        const connection = await this.pool.getConnection();
        try {
            await connection.beginTransaction();
            const result = await work(new MysqlTimeRepository(this.pool, connection));
            if (result.status === 'success')
                await connection.commit();
            else
                await connection.rollback();
            return result;
        }
        catch (error) {
            await connection.rollback();
            throw error;
        }
        finally {
            connection.release();
        }
    }
    async lockPeriods() { await this.rows('SELECT id FROM time_write_guard WHERE id=1 FOR UPDATE'); }
    async lockEmployee(id: string) { return (await this.rows('SELECT id FROM employees WHERE id=? FOR UPDATE', [id])).length === 1; }
    async overlapsClock(employeeId: string, start: string, end: string, excludeId?: string) { return (await this.rows("SELECT id FROM time_entries WHERE employee_id=? AND is_active=TRUE AND status<>'draft' AND start_at_utc<? AND end_at_utc>? AND id<>? LIMIT 1", [employeeId, new Date(end), new Date(start), excludeId ?? ''])).length > 0; }
    async entry(id: string) { const r = (await this.rows('SELECT t.*,p.version_number FROM time_entries t JOIN policy_versions p ON p.id=t.policy_version_id WHERE t.id=?', [id]))[0]; return r ? mapEntry(r) : null; }
    async context(employeeId: string, workDate: string, pinnedPolicyId?: string): Promise<DayContext | null> {
        const employee = (await this.rows("SELECT id FROM employees WHERE id=? AND (hire_date IS NULL OR hire_date<=?)", [employeeId, workDate]))[0];
        if (!employee)
            return null;
        const assignments = await this.rows('SELECT a.*,d.is_government FROM employee_division_assignments a JOIN divisions d ON d.id=a.division_id WHERE a.employee_id=? AND a.is_active=TRUE AND a.effective_from<=? AND (a.effective_to IS NULL OR a.effective_to>=?)', [employeeId, workDate, workDate]);
        const periods = await this.periods();
        const period = periods.find((p) => p.startDate <= workDate && p.endDate >= workDate) ?? null;
        const stored = (await this.rows('SELECT snapshot_json,calculation_context_json,policy_version_id FROM daily_summaries WHERE employee_id=? AND work_date=?', [employeeId, workDate]))[0];
        const pinned = pinnedPolicyId ?? ((period?.status === 'verified' || period?.status === 'amended') && stored ? String(stored.policy_version_id) : null);
        const policies = pinned ? await this.rows('SELECT * FROM policy_versions WHERE id=?', [pinned]) : await this.rows(`SELECT pv.* FROM work_policies wp JOIN policy_versions pv ON pv.id=wp.policy_version_id
      WHERE wp.is_active=TRUE AND wp.effective_from<=? AND (wp.effective_to IS NULL OR wp.effective_to>=?)
      AND pv.effective_from<=? AND (pv.effective_to IS NULL OR pv.effective_to>=?)
      AND (wp.employee_id=? OR (wp.employee_id IS NULL AND (wp.division_id IS NULL OR wp.division_id IN (SELECT division_id FROM employee_division_assignments WHERE employee_id=? AND is_primary=TRUE AND is_active=TRUE AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?)))))
      ORDER BY (wp.employee_id IS NOT NULL) DESC,(wp.division_id IS NOT NULL) DESC,wp.effective_from DESC,pv.version_number DESC LIMIT 1`, [workDate, workDate, workDate, workDate, employeeId, employeeId, workDate, workDate]);
        const p = policies[0];
        if (!p)
            return null;
        const config = json<Record<string, unknown>>(p.configuration, {});
        const policy: WorkPolicy = { ...provenance(p), id: String(p.id), version: Number(p.version_number), name: String(p.policy_key), effectiveFrom: date(p.effective_from), effectiveTo: p.effective_to ? date(p.effective_to) : null, requiredActiveMinutes: Number(p.required_active_minutes), recognizedBreakMinutes: Number(p.recognized_break_minutes), requiredTotalMinutes: Number(p.scheduled_minutes), overtimeThresholdMinutes: Number(config.overtimeThresholdMinutes ?? 480), criticalThresholdMinutes: Number(p.overtime_limit_minutes), workingWeekdays: json<number[]>(config.workingWeekdays, [1, 2, 3, 4, 5]), businessTimezone: String(p.timezone) };
        if (!(stored?.calculation_context_json && (period?.status==='verified'||period?.status==='amended')) && config.crossMidnight && config.crossMidnight !== 'attribute_to_start_date')
            throw new Error('Unsupported cross-midnight policy');
        const weekly = await this.rows('SELECT weekday FROM weekly_holidays WHERE is_active=TRUE AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) AND (division_id IS NULL OR division_id IN(SELECT division_id FROM employee_division_assignments WHERE employee_id=? AND is_active=TRUE AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?)))', [workDate,workDate,employeeId,workDate,workDate]);
        const appliedPolicy = {...policy,workingWeekdays:policy.workingWeekdays.filter(day=>!weekly.some(w=>Number(w.weekday)===(day%7)))};
        const entries = (await this.rows('SELECT t.*,p.version_number FROM time_entries t JOIN policy_versions p ON p.id=t.policy_version_id WHERE t.employee_id=? AND t.work_date=? AND t.is_active=TRUE ORDER BY t.id', [employeeId, workDate])).map(mapEntry);
        const divisions = (await this.rows('SELECT * FROM divisions')).map((r) => ({ ...provenance(r), id: String(r.id), name: String(r.name), code: String(r.division_key), description: r.description ? String(r.description) : null, teamLeadEmployeeId: r.team_lead_employee_id ? String(r.team_lead_employee_id) : null, isActive: Boolean(r.is_active), isRestricted: Boolean(r.is_government) } satisfies Division));
        const projects = (await this.rows('SELECT p.* FROM projects p WHERE EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.employee_id=? AND pm.is_active=TRUE AND pm.effective_from<=? AND (pm.effective_to IS NULL OR pm.effective_to>=?)) OR p.manager_employee_id=?', [employeeId, workDate, workDate, employeeId])).map((r) => ({ ...provenance(r), id: String(r.id), divisionId: String(r.division_id), name: String(r.name), code: String(r.project_code), managerEmployeeId: String(r.manager_employee_id), startDate: date(r.start_date ?? r.created_at), endDate: r.end_date ? date(r.end_date) : null, priority: r.priority as Project['priority'], description: null, estimatedMinutes: Number(r.estimated_minutes ?? 0), budget: { visible: false, reason: 'permission_required' }, completionPercent: Number(r.completion_percent), status: r.status as Project['status'], notes: null, isActive: Boolean(r.is_active), acceptsTimeEntries: Boolean(r.accepts_time_entries), client: r.client_name ? String(r.client_name) : null } satisfies Project));
        const tasks = (await this.rows('SELECT * FROM tasks WHERE is_active=TRUE AND (assignee_employee_id=? OR EXISTS(SELECT 1 FROM task_members tm WHERE tm.task_id=tasks.id AND tm.employee_id=?))', [employeeId, employeeId])).map((r) => ({ ...provenance(r), id: String(r.id), projectId: String(r.project_id), divisionId: String(r.division_id), title: String(r.title), assigneeEmployeeId: String(r.assignee_employee_id), supportingMemberIds: [], creatorEmployeeId: String(r.creator_employee_id), priority: (r.priority ?? 'medium') as Task['priority'], startDate: r.start_date ? date(r.start_date) : null, dueDate: r.due_date ? date(r.due_date) : null, completedDate: null, estimatedMinutes: Number(r.estimated_minutes ?? 0), description: r.description ? String(r.description) : null, status: r.status as Task['status'], reviewState: r.review_state as Task['reviewState'], reviewerEmployeeId: r.reviewer_employee_id ? String(r.reviewer_employee_id) : null, reviewedAt: r.reviewed_at ? iso(r.reviewed_at) : null, reviewNote: r.review_note ? String(r.review_note) : null } satisfies Task));
        const leave = (await this.rows("SELECT portion,leave_type_id FROM leave_requests WHERE employee_id=? AND start_date<=? AND end_date>=? AND status='approved' ORDER BY portion='full_day' DESC LIMIT 1", [employeeId, workDate, workDate]))[0];
        const holiday = (await this.rows(`SELECT h.name FROM holidays h JOIN holiday_calendars c ON c.id=h.calendar_id WHERE h.holiday_date=? AND h.is_active=TRUE AND c.is_active=TRUE AND c.effective_from<=h.holiday_date AND (c.effective_to IS NULL OR c.effective_to>=h.holiday_date) AND (c.division_id IS NULL OR c.division_id IN(SELECT division_id FROM employee_division_assignments WHERE employee_id=? AND is_active=TRUE AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?))) LIMIT 1`, [workDate, employeeId, workDate, workDate]))[0];
        const dailyBreak = (await this.rows("SELECT minutes,reason FROM daily_breaks WHERE employee_id=? AND work_date=? AND source='override'", [employeeId, workDate]))[0];
        const wfh = (await this.rows("SELECT id FROM wfh_requests WHERE employee_id=? AND wfh_date=? AND status='approved' LIMIT 1", [employeeId, workDate])).length > 0;
        const frozen = (period?.status === 'verified' || period?.status === 'amended') ? json<Partial<DayContext>>(stored?.calculation_context_json, {}) : {};
        return { policy: appliedPolicy, policyId: String(p.id), entries, effectiveDivisionIds: assignments.map((a) => String(a.division_id)), divisions, projects, tasks, leave: leave ? { portion: leave.portion === 'full_day' ? 'full_day' : 'half_day', leaveType: String(leave.leave_type_id) } : null, holidayName: holiday ? String(holiday.name) : null, approvedWfh: wfh, breakOverrideMinutes: dailyBreak ? Number(dailyBreak.minutes) : null, breakReason: dailyBreak?.reason ? String(dailyBreak.reason) : null, period, snapshot: json<DailySummary | null>(stored?.snapshot_json, null), ...frozen };
    }
    async saveEntry(e: StoredEntry, expectedVersion?: number) {
        const values = [e.employeeId, e.workDate, e.divisionId, e.projectId, e.taskId, e.policyId, e.timezone, e.entryMethod, e.workLocation, sqlDate(e.startTime), sqlDate(e.endTime), e.activeMinutes, e.workDescription, e.completedWork, e.supportingLink, e.overtimeReason, e.criticalExplanation, e.state, e.isActive, JSON.stringify(e.attachmentIds), e.crossMidnightGroupId, e.version, e.updatedBy.userId];
        if (expectedVersion === undefined) {
            await this.db.execute(`INSERT INTO time_entries(employee_id,work_date,division_id,project_id,task_id,policy_version_id,timezone,entry_method,work_location,start_at_utc,end_at_utc,active_minutes,work_description,completed_work,supporting_link,overtime_reason,critical_explanation,status,is_active,attachment_ids,cross_midnight_group_id,version,updated_by_user_id,id,created_by_user_id) VALUES(${Array(25).fill('?').join(',')})`, [...values, e.id, e.createdBy.userId]);
            return true;
        }
        const [result] = await this.db.execute<ResultSetHeader>('UPDATE time_entries SET employee_id=?,work_date=?,division_id=?,project_id=?,task_id=?,policy_version_id=?,timezone=?,entry_method=?,work_location=?,start_at_utc=?,end_at_utc=?,active_minutes=?,work_description=?,completed_work=?,supporting_link=?,overtime_reason=?,critical_explanation=?,status=?,is_active=?,attachment_ids=?,cross_midnight_group_id=?,version=?,updated_by_user_id=? WHERE id=? AND version=?', [...values, e.id, expectedVersion]);
        return result.affectedRows === 1;
    }
    async saveSummary(s: DailySummary, policyId: string, context: DayContext) { await this.db.execute(`INSERT INTO daily_summaries(id,employee_id,work_date,active_minutes,break_minutes,total_minutes,required_active_minutes,required_break_minutes,classification,timezone,policy_version_id,recalculated_at,source_version,snapshot_json,calculation_context_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(6),1,?,?) ON DUPLICATE KEY UPDATE active_minutes=VALUES(active_minutes),break_minutes=VALUES(break_minutes),total_minutes=VALUES(total_minutes),required_active_minutes=VALUES(required_active_minutes),required_break_minutes=VALUES(required_break_minutes),classification=VALUES(classification),timezone=VALUES(timezone),policy_version_id=VALUES(policy_version_id),recalculated_at=UTC_TIMESTAMP(6),source_version=source_version+1,snapshot_json=VALUES(snapshot_json),calculation_context_json=VALUES(calculation_context_json)`, [randomUUID(), s.employeeId, s.workDate, s.activeMinutes, s.breakMinutes, s.totalMinutes, s.requiredActiveMinutes, Math.max(0, s.requiredTotalMinutes - s.requiredActiveMinutes), s.status, s.timezone, policyId, JSON.stringify(s), JSON.stringify({ policy: context.policy, leave: context.leave, holidayName: context.holidayName, approvedWfh: context.approvedWfh, breakOverrideMinutes: context.breakOverrideMinutes, breakReason: context.breakReason })]); }
    async saveBreak(employeeId: string, date: string, minutes: number, reason: string, policyId: string) { await this.db.execute("INSERT INTO daily_breaks(id,employee_id,work_date,minutes,source,reason,policy_version_id) VALUES(?,?,?,?,'override',?,?) ON DUPLICATE KEY UPDATE minutes=VALUES(minutes),source='override',reason=VALUES(reason),policy_version_id=VALUES(policy_version_id),version=version+1", [randomUUID(), employeeId, date, minutes, reason, policyId]); }
    async timer(id: string) { const r = (await this.rows('SELECT * FROM timer_sessions WHERE id=?', [id]))[0]; return r ? mapTimer(r) : null; }
    async runningTimer(employeeId: string) { const r = (await this.rows('SELECT * FROM timer_sessions WHERE running_employee_id=?', [employeeId]))[0]; return r ? mapTimer(r) : null; }
    async saveTimer(t: StoredTimer, actorId: string) { await this.db.execute(`INSERT INTO timer_sessions(id,employee_id,division_id,project_id,task_id,work_location,started_at_utc,stopped_at_utc,cancelled_at_utc,timezone,policy_version_id,draft_time_entry_id,draft_payload,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE stopped_at_utc=VALUES(stopped_at_utc),cancelled_at_utc=VALUES(cancelled_at_utc),draft_time_entry_id=VALUES(draft_time_entry_id),draft_payload=VALUES(draft_payload),version=version+1`, [t.id, t.employeeId, t.divisionId, t.projectId, t.taskId, t.workLocation, sqlDate(t.startedAt), sqlDate(t.stoppedAt), sqlDate(t.cancelledAt), t.timezone, t.policyId, t.draftTimeEntryId, JSON.stringify(t.draft), actorId]); }
    async replay(actor: string, operation: string, key: string) { const r = (await this.rows('SELECT request_hash,response_body FROM idempotency_records WHERE actor_user_id=? AND operation_key=? AND idempotency_key=?', [actor, operation, key]))[0]; return r ? { hash: String(r.request_hash), result: json<Result<unknown>>(r.response_body, { status: 'success', data: null }) } : null; }
    async remember(actor: string, operation: string, key: string, hash: string, result: Result<unknown>) { await this.db.execute("INSERT INTO idempotency_records(id,actor_user_id,operation_key,idempotency_key,request_hash,response_status,response_body,expires_at) VALUES(?,?,?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 365 DAY))", [randomUUID(), actor, operation, key, hash, result.status, JSON.stringify(result)]); }
    async audit(e: TimeAudit) { await this.db.execute('INSERT INTO audit_events(event_id,actor_user_id,action,resource_type,resource_id,scope_json,reason,correlation_id,before_protected,after_protected) VALUES(?,?,?,?,?,?,?,?,?,?)', [randomUUID(), e.actorUserId, e.action, 'time', e.resourceId, JSON.stringify({ employeeId: e.employeeId }), e.reason ?? null, e.correlationId, JSON.stringify(redactProtected(e.before)), JSON.stringify(redactProtected(e.after))]); }
    async enqueue(key: string, type: string, employeeId: string, date: string) {
        await this.db.execute('INSERT INTO time_outbox(id,event_key,event_type,employee_id,work_date) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE event_key=event_key', [randomUUID(), key, type, employeeId, date]);
        if (type === 'time.critical' || type.startsWith('time.remark.') || type === 'time.period.amended') {
            const recipients = await this.rows(`SELECT DISTINCT u.id FROM users u LEFT JOIN employees e ON e.user_id=u.id
        WHERE u.status='active' AND (e.id IN(SELECT lead_employee_id FROM employee_division_assignments WHERE employee_id=? AND is_active=TRUE AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?))
        OR EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=u.id AND (r.role_key='hr_manager' OR (?='time.period.amended' AND r.role_key='finance_manager')) AND ur.effective_from<=? AND (ur.effective_to IS NULL OR ur.effective_to>=?))
        OR (? LIKE 'time.remark.%' AND e.id=?))`, [employeeId, date, date, type, date, date, type, employeeId]);
            for (const recipient of recipients)
                await this.db.execute("INSERT INTO notifications(id,recipient_user_id,notification_type,safe_payload,related_type,related_id,deduplication_key) VALUES(?,?,?,?,'timesheet',?,?) ON DUPLICATE KEY UPDATE deduplication_key=deduplication_key", [randomUUID(), String(recipient.id), type, JSON.stringify({ message: 'A timesheet record requires your attention.' }), employeeId, createHash('sha256').update(type + ':' + key).digest('hex')]);
        }
    }
    async taskRemarkAllowed(taskId: string, employeeId: string, actor: ActorPolicyContext) {
        const rows = await this.rows('SELECT t.id,p.is_active,d.is_government FROM tasks t JOIN projects p ON p.id=t.project_id JOIN divisions d ON d.id=p.division_id WHERE t.id=? AND (t.assignee_employee_id=? OR EXISTS(SELECT 1 FROM task_members m WHERE m.task_id=t.id AND m.employee_id=?))', [taskId, employeeId, employeeId]);
        return rows.length === 1 && (!rows[0].is_government || hasPermission(actor, 'organization.government.view'));
    }
    async attachmentAllowed(id: string, employeeId: string, actor: ActorPolicyContext) { if (!hasPermission(actor, 'file.protected.view'))
        return false; return (await this.rows("SELECT a.id FROM attachments a JOIN employees e ON e.user_id=a.uploaded_by_user_id WHERE a.id=? AND e.id=? AND a.scan_status='clean' AND a.deactivated_at IS NULL", [id, employeeId])).length === 1; }
    async employeeRef(id: string) { const r = (await this.rows('SELECT id,display_name,employee_code,job_title FROM employees WHERE id=?', [id]))[0]; return r ? { id: String(r.id), fullName: String(r.display_name), employeeCode: String(r.employee_code), designation: r.job_title ? String(r.job_title) : null, avatarUrl: null } : null; }
    async employeeIds() { return (await this.rows("SELECT id FROM employees WHERE status='active' ORDER BY id")).map((r) => String(r.id)); }
    async periods() { return (await this.rows('SELECT t.*,p.version_number FROM timesheet_periods t JOIN policy_versions p ON p.id=t.policy_version_id ORDER BY t.start_date,t.id')).map((r) => ({ ...provenance(r), id: String(r.id), label: String(r.label), startDate: date(r.start_date), endDate: date(r.end_date), status: r.status as StoredPeriod['status'], verifiedAt: r.verified_at ? iso(r.verified_at) : null, verifiedBy: r.verified_by_user_id ? { userId: String(r.verified_by_user_id), displayName: 'HR' } : null, policyVersion: Number(r.version_number), policyId: String(r.policy_version_id), version: Number(r.version), includedEmployeeCount: 0, openExceptionCount: 0 })); }
    async savePeriod(p: StoredPeriod) { await this.db.execute('UPDATE timesheet_periods SET status=?,verified_at=?,verified_by_user_id=?,version=? WHERE id=?', [p.status, sqlDate(p.verifiedAt), p.verifiedBy?.userId ?? null, p.version, p.id]); }
    async verification(p: StoredPeriod, summaries: readonly DailySummary[], actorId: string, note: string | null) { const snapshot = JSON.stringify(summaries); await this.db.execute('INSERT INTO period_verifications(id,period_id,verified_by_user_id,verified_at,note,policy_version_id,snapshot_hash,snapshot_json) VALUES(?,?,?,UTC_TIMESTAMP(6),?,?,?,?)', [randomUUID(), p.id, actorId, note, p.policyId, createHash('sha256').update(snapshot).digest('hex'), snapshot]); }
    async remarks(employeeId: string) { return (await this.rows(`SELECT r.*,e.id author_employee_id,te.work_date legacy_work_date FROM general_remarks r JOIN employees e ON e.user_id=r.author_user_id LEFT JOIN time_entries te ON r.related_type='time_entry' AND te.id=r.related_id AND te.employee_id=r.employee_id WHERE r.employee_id=? ORDER BY r.created_at,r.id`, [employeeId])).map(mapRemark); }
    async remark(id: string) { const r = (await this.rows(`SELECT r.*,e.id author_employee_id,te.work_date legacy_work_date FROM general_remarks r JOIN employees e ON e.user_id=r.author_user_id LEFT JOIN time_entries te ON r.related_type='time_entry' AND te.id=r.related_id AND te.employee_id=r.employee_id WHERE r.id=?`, [id]))[0]; return r ? mapRemark(r) : null; }
    async saveRemark(r: GeneralRemark, actorId: string) { await this.db.execute(`INSERT INTO general_remarks(id,employee_id,author_user_id,message,related_type,related_id,related_work_date,is_correction_request,requested_changes,status,responses_json) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),responses_json=VALUES(responses_json),version=version+1`, [r.id, r.employeeId, actorId, r.message, r.relatedRecord.type, r.relatedRecord.type === 'task' ? r.relatedRecord.taskId : null, r.relatedRecord.type === 'timesheet' ? r.relatedRecord.workDate : null, r.isCorrectionRequest, r.requestedChanges, r.state, JSON.stringify(r.responses)]); }
}
function mapEntry(r: Row): StoredEntry { return { ...provenance(r), id: String(r.id), employeeId: String(r.employee_id), workDate: date(r.work_date), divisionId: String(r.division_id), projectId: r.project_id ? String(r.project_id) : null, taskId: r.task_id ? String(r.task_id) : null, policyId: String(r.policy_version_id), policyVersion: Number(r.version_number), timezone: String(r.timezone), entryMethod: r.entry_method as StoredEntry['entryMethod'], workLocation: r.work_location as StoredEntry['workLocation'], startTime: r.start_at_utc ? iso(r.start_at_utc) : null, endTime: r.end_at_utc ? iso(r.end_at_utc) : null, activeMinutes: Number(r.active_minutes), workDescription: String(r.work_description), completedWork: String(r.completed_work), supportingLink: r.supporting_link ? String(r.supporting_link) : null, overtimeReason: r.overtime_reason ? String(r.overtime_reason) : null, criticalExplanation: r.critical_explanation ? String(r.critical_explanation) : null, state: r.status as StoredEntry['state'], isActive: Boolean(r.is_active), attachmentIds: json<string[]>(r.attachment_ids, []), crossMidnightGroupId: r.cross_midnight_group_id ? String(r.cross_midnight_group_id) : null, version: Number(r.version) }; }
function mapTimer(r: Row): StoredTimer { return { id: String(r.id), employeeId: String(r.employee_id), divisionId: String(r.division_id), projectId: r.project_id ? String(r.project_id) : null, taskId: r.task_id ? String(r.task_id) : null, workLocation: r.work_location as StoredTimer['workLocation'], startedAt: iso(r.started_at_utc), stoppedAt: r.stopped_at_utc ? iso(r.stopped_at_utc) : null, cancelledAt: r.cancelled_at_utc ? iso(r.cancelled_at_utc) : null, isRunning: !r.stopped_at_utc && !r.cancelled_at_utc, timezone: String(r.timezone), policyId: String(r.policy_version_id), draftTimeEntryId: r.draft_time_entry_id ? String(r.draft_time_entry_id) : null, draft: json<StoredTimer['draft']>(r.draft_payload, null) }; }
function mapRemark(r: Row): GeneralRemark { return { ...provenance(r), id: String(r.id), employeeId: String(r.employee_id), authorEmployeeId: String(r.author_employee_id), message: String(r.message), relatedRecord: r.related_type === 'timesheet' || r.legacy_work_date ? { type: 'timesheet', workDate: date(r.related_work_date ?? r.legacy_work_date) } : r.related_type === 'task' ? { type: 'task', taskId: String(r.related_id) } : { type: 'none' }, isCorrectionRequest: Boolean(r.is_correction_request), requestedChanges: r.requested_changes ? String(r.requested_changes) : null, state: r.status as GeneralRemark['state'], responses: json<GeneralRemark['responses']>(r.responses_json, []) }; }
