import { randomUUID } from 'node:crypto';
import type { ActorPolicyContext } from '@/server/authorization/policy';
import { authorizeMutation, readAuthorized } from '@/server/authorization/gateway';
import { taskDerivedFacts, validateProject, validateTaskScope } from '@/server/organization/rules';

export type ProjectState='planned'|'active'|'on_hold'|'completed'|'closed';
export interface ProjectRecord { id:string;divisionId:string;managerEmployeeId:string;name:string;code:string;status:ProjectState;isActive:boolean;acceptsTime:boolean;completionPercent:number;startDate:string|null;endDate:string|null;estimatedMinutes:number;budgetAmount:string|null;currency:string|null;client:string|null;notes:string|null;version:number;references:number }
export interface TaskRecord { id:string;projectId:string;divisionId:string;assigneeEmployeeId:string;supportingMemberIds:readonly string[];title:string;status:'pending'|'in_progress'|'completed';dueDate:string|null;estimatedMinutes:number;version:number }
export interface WorkRepository {
  transaction<T>(work:()=>Promise<T>):Promise<T>; effectiveDivisions(id:string,date:string):Promise<readonly string[]>;
  project(id:string):Promise<ProjectRecord|null>; saveProject(row:ProjectRecord,version:number|null):Promise<boolean>; setProjectMembers(id:string,members:readonly string[],date:string):Promise<void>; projectActualMinutes(id:string):Promise<number>;
  task(id:string):Promise<TaskRecord|null>; saveTask(row:TaskRecord,version:number|null):Promise<boolean>; setSupportingMembers(id:string,members:readonly string[]):Promise<void>; replaceChecklist(id:string,items:readonly{label:string;position:number}[]):Promise<void>; setChecklistItem(taskId:string,itemId:string,done:boolean,version:number):Promise<boolean>; taskActualEntries(id:string):Promise<readonly{activeMinutes:number;isActive:boolean}[]>;
  listTasks(input:{employeeIds:readonly string[];projectIds:readonly string[];status?:string;dueBefore?:string;term?:string;offset:number;limit:number;sort:'title'|'due_date'|'status';direction:'ASC'|'DESC'}):Promise<{rows:readonly TaskRecord[];total:number}>;
}
export interface WorkAudit { append(action:string,actor:string,type:string,id:string,before:unknown,after:unknown):Promise<void> }
const denied=(p:string)=>({status:'permission_denied' as const,code:'FORBIDDEN' as const,message:'You do not have permission.',requiredPermission:p});
const stale=()=>({status:'conflict' as const,code:'CONFLICT' as const,message:'The record changed.',guidance:'Refresh and try again.'});

export class WorkApplicationService {
  constructor(private repo:WorkRepository,private audit:WorkAudit){}
  async saveProject(actor:ActorPolicyContext,input:Omit<ProjectRecord,'id'|'version'|'references'>&{id?:string;memberIds:readonly string[];effectiveDate:string}){
    if(authorizeMutation(actor,'project.manage',{divisionId:input.divisionId},'server_action').status!=='success')return denied('project.manage');
    const before=input.id?await this.repo.project(input.id):null;if(input.id&&!before)return readAuthorized(actor,'project.manage',null,'server_action');
    const managerDivisionIds=await this.repo.effectiveDivisions(input.managerEmployeeId,input.effectiveDate);const invalid=validateProject({...input,managerDivisionIds});if(invalid)return invalid;
    for(const member of input.memberIds)if(!(await this.repo.effectiveDivisions(member,input.effectiveDate)).includes(input.divisionId))return{status:'validation_failure' as const,code:'VALIDATION_FAILED' as const,message:'A member is outside the project division.',fieldErrors:[{field:'memberIds',code:'MEMBER_OUT_OF_SCOPE',message:'A member lacks an effective division assignment.',guidance:'Choose members assigned to this division.'}]};
    const{id,memberIds,effectiveDate,...data}=input;void effectiveDate;const row:ProjectRecord={...data,id:id??randomUUID(),version:(before?.version??0)+1,references:before?.references??0};
    const saved=await this.repo.transaction(async()=>{if(!(await this.repo.saveProject(row,before?.version??null)))return false;await this.repo.setProjectMembers(row.id,memberIds,input.effectiveDate);return true});if(!saved)return stale();await this.audit.append(before?'project.updated':'project.created',actor.userId,'project',row.id,before,row);return{status:'success' as const,data:{...row,actualMinutes:await this.repo.projectActualMinutes(row.id)}};
  }
  async setProjectState(actor:ActorPolicyContext,id:string,status:ProjectState){const before=await this.repo.project(id);if(!before)return readAuthorized(actor,'project.manage',null,'server_action');if(authorizeMutation(actor,'project.manage',{divisionId:before.divisionId},'server_action').status!=='success')return denied('project.manage');const row={...before,status,isActive:!['completed','closed'].includes(status),acceptsTime:status==='active',version:before.version+1};if(!(await this.repo.saveProject(row,before.version)))return stale();await this.audit.append('project.status.changed',actor.userId,'project',id,before,row);return{status:'success' as const,data:row}}
  async saveTask(actor:ActorPolicyContext,input:Omit<TaskRecord,'id'|'version'>&{id?:string;checklist:readonly string[];effectiveDate:string}){const project=await this.repo.project(input.projectId);if(!project)return readAuthorized(actor,'task.manage',null,'server_action');if(authorizeMutation(actor,'task.manage',{divisionId:project.divisionId,projectId:project.id},'server_action').status!=='success')return denied('task.manage');const assigneeDivisionIds=await this.repo.effectiveDivisions(input.assigneeEmployeeId,input.effectiveDate);const invalid=validateTaskScope({taskDivisionId:input.divisionId,projectDivisionId:project.divisionId,assigneeDivisionIds});if(invalid)return invalid;const before=input.id?await this.repo.task(input.id):null;const{id,checklist,effectiveDate,...data}=input;void effectiveDate;const row:TaskRecord={...data,id:id??randomUUID(),version:(before?.version??0)+1};const saved=await this.repo.transaction(async()=>{if(!(await this.repo.saveTask(row,before?.version??null)))return false;await this.repo.setSupportingMembers(row.id,row.supportingMemberIds);await this.repo.replaceChecklist(row.id,checklist.map((label,position)=>({label,position})));return true});if(!saved)return stale();await this.audit.append(before?'task.updated':'task.created',actor.userId,'task',row.id,before,row);return{status:'success' as const,data:row}}
  async setTaskStatus(actor:ActorPolicyContext,id:string,status:TaskRecord['status']){const before=await this.repo.task(id);if(!before)return readAuthorized(actor,'task.manage',null,'server_action');if(authorizeMutation(actor,'task.manage',{divisionId:before.divisionId,projectId:before.projectId},'server_action').status!=='success')return denied('task.manage');const allowed={pending:['in_progress'],in_progress:['pending','completed'],completed:['in_progress']} as const;if(before.status!==status&&!(allowed[before.status] as readonly string[]).includes(status))return{status:'conflict' as const,code:'CONFLICT' as const,message:'That task status transition is not allowed.',guidance:'Refresh and choose an available status.'};const row={...before,status,version:before.version+1};if(!(await this.repo.saveTask(row,before.version)))return stale();return{status:'success' as const,data:row}}
  async taskFacts(actor:ActorPolicyContext,id:string,today:string){const task=await this.repo.task(id);if(!task)return readAuthorized(actor,'task.assigned.read',null,'server_component');return{status:'success' as const,data:{...task,...taskDerivedFacts(await this.repo.taskActualEntries(id),task.status,task.dueDate,today)}}}
  async listTasks(actor:ActorPolicyContext,input:Parameters<WorkRepository['listTasks']>[0]){return{status:'success' as const,data:await this.repo.listTasks({...input,employeeIds:input.employeeIds.filter(id=>actor.employeeIds.has(id)),projectIds:input.projectIds.filter(id=>actor.projectIds.has(id)),limit:Math.min(100,Math.max(1,input.limit)),offset:Math.max(0,input.offset)})}}
}
